# Site settings
title: Spyridon Pagiatis
description: Full Stack Developer Project Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spyridon Pagiatis
user_description: I’m an aspiring full stack developer with a strong foundation in analytical thinking and problem-solving. Having recently completed a hands-on Full Stack Developer Bootcamp, I’ve developed skills in HTML5, CSS, React, JavaScript, SQL and C#.
user_title: Full Stack Developer
email: spiridonpagiatis@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: spyridonpagiatis
github_username:  SpPag
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

